export default {
  'getting-started': '시작하기',
  troubleshooting: '트러블슈팅',
  components: '컴포넌트',
  extensions: '확장',
  collaboration: '실시간 협업',
  'image-editor': '이미지 에디터',
  ssr: 'SSR',
  serialization: '직렬화',
  adapter: '어댑터',
  'i18n-locale': 'i18n & Locale',
  'overlay-positioning': 'Overlay Positioning',
  frameworks: '프레임워크 통합',
  recipes: '레시피',
  playground: '플레이그라운드',
  development: '개발 가이드',
};
