packages:
  - 'packages/core'
  - 'packages/essential'
  - 'packages/advanced'
  - 'packages/simple'
  - 'packages/editor'
  - 'packages/image-editor'
  - 'docs'
  - 'examples/*'
autoInstallPeers: false
preferWorkspacePackages: true
linkWorkspacePackages: true
