packages:
  - 'packages/core'
  - 'packages/advanced'
  - 'packages/simple'
  - 'packages/editor'
  - 'packages/image-editor'
  - 'docs'
  - 'examples/*'
overrides:
  '@asamuzakjp/css-color': ^4.1.2
autoInstallPeers: false
preferWorkspacePackages: true
linkWorkspacePackages: true
