export {
  ArrowIcon,
  BoldIcon,
  CropIcon,
  EllipseIcon,
  FlipHIcon,
  FlipVIcon,
  ItalicIcon,
  LockClosedIcon as LockIcon,
  LockOpenIcon as UnlockIcon,
  MaximizeIcon as ResizeIcon,
  MinusIcon as LineIcon,
  PencilIcon,
  RectIcon,
  RedoIcon,
  RotateCCWIcon,
  RotateCWIcon,
  ShapesIcon,
  TypeIcon,
  UndoIcon,
  XIcon as CloseIcon,
} from '@inkio/core/icons';
